version: 2

multi-ecosystem-groups:
  python:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "pip"
    directory: "/"
    multi-ecosystem-group: python
    patterns: ["*"]
  - package-ecosystem: "uv"
    directory: "/"
    multi-ecosystem-group: python
    patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
